import Head from "next/head";
import Logo from "./Logo";
import Sidebar from "./Sidebar";

const Layout = ({children}) => {
  return ( 
    <div className="h-screen flex w-screen overflow-hidden bg-gray-300">
              <Head>
        <title>Ne - Nouvelle Ecole</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full max-w-2xl mx-auto">
      <Sidebar/>
      
      <main className="flex flex-col w-full items-center justify-center bg-gray-300">
      <Logo />
      {children} 
      </main>
      
    </div>


</div>

   );
}
 
export default Layout;